### ISSUE TITLE
How to get the visualization results?

### ISSUE THREAD

**Issue by ZJU-PLP** [dongbo-BUAA-VR/Pointfilter#2]
Dear author:
     Thanks for sharing a so nice project.
     However, I can not find **the visualization code** in your released code for your results. Could you mind sharing this part or providing some tools?
    Thanks in advance!

**Comment by dongbo-BUAA-VR** [comment]
You could use vedo for visualization ([a lightweight python module](https://github.com/marcomusy/vedo)), or save result in *.ply formate and show it via [meshlab](https://www.meshlab.net/)
